/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Jefferson Queiroz
 */
public class CadastroLeitor extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroLeitor
     */
    public CadastroLeitor() {
        initComponents();
    }

    CadastroLeitor(TelaPrincipal aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelCadastroLeitor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmailCadastroLeitor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEnderecoCadastroLeitor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBairroCadastroLeitor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidadeCadastroLeitor = new javax.swing.JTextField();
        jComboBoxUfCadastroLeitor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeCadastroLeitor = new javax.swing.JTextField();
        jButtonOkCadastroLeitor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonCancelarCadastroLeitor = new javax.swing.JButton();
        jButtonFecharCadastroLeitor = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNumeroCadastroLeitor = new javax.swing.JTextField();
        jFormattedTextFieldCepCadastroLeitor = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpfCadastroLeitor = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDtNascimentoCadastroLeitor = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefoneCadastroLeitor = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Sistema de Biblioteca - Cadastro de Leitor");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setText("Cadastro de Leitor");
        jLabel10.setToolTipText("Cadastro de Leitor");

        jPanelCadastroLeitor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("E-mail");

        jTextFieldEmailCadastroLeitor.setToolTipText("Informe o E-mail");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Endereço");

        jTextFieldEnderecoCadastroLeitor.setToolTipText("Informe o endereço");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Bairro");

        jTextFieldBairroCadastroLeitor.setToolTipText("Informe o bairro");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Telefone");

        jLabelCidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCidade.setText("Cidade");

        jTextFieldCidadeCadastroLeitor.setToolTipText("Informe a cidade");

        jComboBoxUfCadastroLeitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC  ", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR ", "RS", "SC", "SE", "SP", "TO" }));
        jComboBoxUfCadastroLeitor.setToolTipText("Escoha a Unidade Federativa");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("UF");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("CEP");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("CPF");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nome do Leitor ");

        jTextFieldNomeCadastroLeitor.setToolTipText("Informa o nome do leitor");
        jTextFieldNomeCadastroLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCadastroLeitorActionPerformed(evt);
            }
        });

        jButtonOkCadastroLeitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonOkCadastroLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ok.png"))); // NOI18N
        jButtonOkCadastroLeitor.setText("OK");
        jButtonOkCadastroLeitor.setToolTipText("Confirmar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Data de Nasc.");

        jButtonCancelarCadastroLeitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelarCadastroLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel.png"))); // NOI18N
        jButtonCancelarCadastroLeitor.setText("Cancelar");
        jButtonCancelarCadastroLeitor.setToolTipText("Cancelar");

        jButtonFecharCadastroLeitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonFecharCadastroLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fechar.png"))); // NOI18N
        jButtonFecharCadastroLeitor.setText("Fechar");
        jButtonFecharCadastroLeitor.setToolTipText("Fechar");
        jButtonFecharCadastroLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharCadastroLeitorActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Número");

        try {
            jFormattedTextFieldCepCadastroLeitor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldCpfCadastroLeitor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldDtNascimentoCadastroLeitor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldTelefoneCadastroLeitor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanelCadastroLeitorLayout = new javax.swing.GroupLayout(jPanelCadastroLeitor);
        jPanelCadastroLeitor.setLayout(jPanelCadastroLeitorLayout);
        jPanelCadastroLeitorLayout.setHorizontalGroup(
            jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelCidade)
                                        .addComponent(jTextFieldEnderecoCadastroLeitor)
                                        .addComponent(jTextFieldCidadeCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5))
                                .addGap(54, 54, 54)
                                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldNumeroCadastroLeitor)
                                    .addComponent(jLabel12)
                                    .addComponent(jComboBoxUfCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldBairroCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLeitorLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextFieldCepCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 49, Short.MAX_VALUE))))
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldDtNascimentoCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldCpfCadastroLeitor)
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldTelefoneCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldEmailCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomeCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jButtonOkCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelarCadastroLeitor)
                .addGap(18, 18, 18)
                .addComponent(jButtonFecharCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastroLeitorLayout.setVerticalGroup(
            jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNomeCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldDtNascimentoCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextFieldCpfCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldTelefoneCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmailCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEnderecoCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCidadeCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNumeroCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldBairroCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxUfCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldCepCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(26, 26, 26)))))
                .addGap(34, 34, 34)
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonOkCadastroLeitor)
                    .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonFecharCadastroLeitor)
                        .addComponent(jButtonCancelarCadastroLeitor)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel10)
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addComponent(jPanelCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeCadastroLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCadastroLeitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCadastroLeitorActionPerformed

    private void jButtonFecharCadastroLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCadastroLeitorActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharCadastroLeitorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarCadastroLeitor;
    private javax.swing.JButton jButtonFecharCadastroLeitor;
    private javax.swing.JButton jButtonOkCadastroLeitor;
    private javax.swing.JComboBox<String> jComboBoxUfCadastroLeitor;
    private javax.swing.JFormattedTextField jFormattedTextFieldCepCadastroLeitor;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfCadastroLeitor;
    private javax.swing.JFormattedTextField jFormattedTextFieldDtNascimentoCadastroLeitor;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefoneCadastroLeitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JPanel jPanelCadastroLeitor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBairroCadastroLeitor;
    private javax.swing.JTextField jTextFieldCidadeCadastroLeitor;
    private javax.swing.JTextField jTextFieldEmailCadastroLeitor;
    private javax.swing.JTextField jTextFieldEnderecoCadastroLeitor;
    private javax.swing.JTextField jTextFieldNomeCadastroLeitor;
    private javax.swing.JTextField jTextFieldNumeroCadastroLeitor;
    // End of variables declaration//GEN-END:variables

    void setLocationRelatveTo(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
