/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Jefferson Queiroz
 */
public class ConsultaLeitor extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarLeitor
     */
    public ConsultaLeitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel10 = new javax.swing.JLabel();
        jPanelCadastroLeitor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEnderecoConsultaLeitor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBairroConsultaLeitor = new javax.swing.JTextField();
        jFormattedTextFieldDtNascimentoConsultaLeitor = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTelefoneConsultaLeitor = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidadeConsultaLeitor = new javax.swing.JTextField();
        jComboBoxUfConsultaLeitor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCepConsultaLeitor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldCpfConsultaLeitor = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeConsultaLeitor = new javax.swing.JTextField();
        jButtonOkCadastroLeitor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonFecharCadastroLeitor = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNumeroConsultaLeitor = new javax.swing.JTextField();
        jButtonPesquisaConsultaLeitor = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setClosable(true);
        setIconifiable(true);
        setTitle("Sistema de Biblioteca - Consultar Leitor");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setText("Consultar Leitor");
        jLabel10.setToolTipText("Cadastro de Leitor");

        jPanelCadastroLeitor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("E-mail");

        jTextFieldEmail.setToolTipText("Informe o E-mail");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Endereço");

        jTextFieldEnderecoConsultaLeitor.setToolTipText("Informe o endereço");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Bairro");

        jTextFieldBairroConsultaLeitor.setToolTipText("Informe o bairro");

        jFormattedTextFieldDtNascimentoConsultaLeitor.setToolTipText("Informe a data de nascimento 14/05/1997");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Telefone");

        jTextFieldTelefoneConsultaLeitor.setToolTipText("Informe o telefone");

        jLabelCidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCidade.setText("Cidade");

        jTextFieldCidadeConsultaLeitor.setToolTipText("Informe a cidade");

        jComboBoxUfConsultaLeitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC  ", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR ", "RS", "SC", "SE", "SP", "TO" }));
        jComboBoxUfConsultaLeitor.setToolTipText("Escoha a Unidade Federativa");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("UF");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("CEP");

        jTextFieldCepConsultaLeitor.setToolTipText("Informe o CEP");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("CPF");

        jTextFieldCpfConsultaLeitor.setToolTipText("Informe o CPF");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nome do Leitor ");

        jTextFieldNomeConsultaLeitor.setToolTipText("Informa o nome do leitor");
        jTextFieldNomeConsultaLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeConsultaLeitorActionPerformed(evt);
            }
        });

        jButtonOkCadastroLeitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonOkCadastroLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ok.png"))); // NOI18N
        jButtonOkCadastroLeitor.setText("OK");
        jButtonOkCadastroLeitor.setToolTipText("Confirmar");
        jButtonOkCadastroLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkCadastroLeitorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Data de Nasc.");

        jButtonFecharCadastroLeitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonFecharCadastroLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fechar.png"))); // NOI18N
        jButtonFecharCadastroLeitor.setText("Fechar");
        jButtonFecharCadastroLeitor.setToolTipText("Fechar");
        jButtonFecharCadastroLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharCadastroLeitorActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Número");

        jButtonPesquisaConsultaLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lupa.png"))); // NOI18N
        jButtonPesquisaConsultaLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaConsultaLeitorActionPerformed(evt);
            }
        });

        jLabel11.setText("Clique para pesquisar");

        javax.swing.GroupLayout jPanelCadastroLeitorLayout = new javax.swing.GroupLayout(jPanelCadastroLeitor);
        jPanelCadastroLeitor.setLayout(jPanelCadastroLeitorLayout);
        jPanelCadastroLeitorLayout.setHorizontalGroup(
            jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldDtNascimentoConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addComponent(jTextFieldCpfConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTelefoneConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNomeConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisaConsultaLeitor)
                        .addGap(199, 199, 199))
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelCidade)
                                .addComponent(jTextFieldEnderecoConsultaLeitor)
                                .addComponent(jTextFieldCidadeConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNumeroConsultaLeitor, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBoxUfConsultaLeitor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldCepConsultaLeitor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldBairroConsultaLeitor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(28, 28, 28))
                            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jButtonOkCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jButtonFecharCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastroLeitorLayout.setVerticalGroup(
            jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNomeConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jFormattedTextFieldDtNascimentoConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonPesquisaConsultaLeitor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCpfConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldTelefoneConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEnderecoConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBairroConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNumeroConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCidade)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCidadeConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxUfConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCepConsultaLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFecharCadastroLeitor)
                    .addComponent(jButtonOkCadastroLeitor))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel10)
                        .addGap(326, 326, 326))
                    .addComponent(jPanelCadastroLeitor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanelCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeConsultaLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeConsultaLeitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeConsultaLeitorActionPerformed

    private void jButtonFecharCadastroLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCadastroLeitorActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharCadastroLeitorActionPerformed

    private void jButtonPesquisaConsultaLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaConsultaLeitorActionPerformed
     /* ConsultaLeitor2 consulta2 = new ConsultaLeitor2(this, true);
       consulta2.setVisible(true);*/
      
        //ConsultaLeitorDois consultaDois = new ConsultaLeitor2();
        //consultaDois.add(consultaDois);
         //this.desktopPane.add(consultaDois);
          // consultaDois.setVisible(true);
        
        //new ConsultaLeitor2().setVisible(true); poloma
        
        ConsultaLeitor2 consultaLeitor2 = new ConsultaLeitor2();
        TelaPrincipal.desktopPane.add(consultaLeitor2);
        consultaLeitor2.setVisible(true);
      
    
      
        
        
    }//GEN-LAST:event_jButtonPesquisaConsultaLeitorActionPerformed

    private void jButtonOkCadastroLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkCadastroLeitorActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOkCadastroLeitorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFecharCadastroLeitor;
    private javax.swing.JButton jButtonOkCadastroLeitor;
    private javax.swing.JButton jButtonPesquisaConsultaLeitor;
    private javax.swing.JComboBox<String> jComboBoxUfConsultaLeitor;
    private javax.swing.JFormattedTextField jFormattedTextFieldDtNascimentoConsultaLeitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanelCadastroLeitor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBairroConsultaLeitor;
    private javax.swing.JTextField jTextFieldCepConsultaLeitor;
    private javax.swing.JTextField jTextFieldCidadeConsultaLeitor;
    private javax.swing.JTextField jTextFieldCpfConsultaLeitor;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEnderecoConsultaLeitor;
    private javax.swing.JTextField jTextFieldNomeConsultaLeitor;
    private javax.swing.JTextField jTextFieldNumeroConsultaLeitor;
    private javax.swing.JTextField jTextFieldTelefoneConsultaLeitor;
    // End of variables declaration//GEN-END:variables
}
