/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Imagens.Salvo;

/**
 *
 * @author Jefferson Queiroz
 */
public class EditarLeitor extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroLeitor
     */
    public EditarLeitor() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelCadastroLeitor = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEmailEditarLeitor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEnderecoEditarLeitor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBairroEditarLeitor = new javax.swing.JTextField();
        jFormattedTextFieldDtNascimentoEditarLeitor = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidadeEditarLeitor = new javax.swing.JTextField();
        jComboBoxUfEditarLeitor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeEditarLeitor = new javax.swing.JTextField();
        jButtonSalvarEditarLeitor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonCancelarEditarLeitor = new javax.swing.JButton();
        jButtonFecharEditarLeitor = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNumeroEditarLeitor = new javax.swing.JTextField();
        jButtonPesquisarEditarLeitor = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextFieldCpfEditarLeitor = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefoneEditarLeitor = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCepEditarLeitor = new javax.swing.JFormattedTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Sistema de Biblioteca - Editar Leitor");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setText("Edição de Leitor");
        jLabel10.setToolTipText("Cadastro de Leitor");

        jPanelCadastroLeitor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("E-mail");

        jTextFieldEmailEditarLeitor.setText("jefferson@gmail.com");
        jTextFieldEmailEditarLeitor.setToolTipText("Informe o E-mail");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Endereço");

        jTextFieldEnderecoEditarLeitor.setText("Rua José Eclides");
        jTextFieldEnderecoEditarLeitor.setToolTipText("Informe o endereço");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Bairro");

        jTextFieldBairroEditarLeitor.setText("Boa Vista");
        jTextFieldBairroEditarLeitor.setToolTipText("Informe o bairro");

        try {
            jFormattedTextFieldDtNascimentoEditarLeitor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDtNascimentoEditarLeitor.setToolTipText("Informe a data de nascimento 14/05/1997");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Telefone");

        jLabelCidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCidade.setText("Cidade");

        jTextFieldCidadeEditarLeitor.setText("Recife");
        jTextFieldCidadeEditarLeitor.setToolTipText("Informe a cidade");

        jComboBoxUfEditarLeitor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PE", "AC  ", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR ", "RS", "SC", "SE", "SP", "TO" }));
        jComboBoxUfEditarLeitor.setToolTipText("Escoha a Unidade Federativa");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("UF");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("CEP");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("CPF");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nome do Leitor ");

        jTextFieldNomeEditarLeitor.setText("Jefferson Queiroz");
        jTextFieldNomeEditarLeitor.setToolTipText("Informa o nome do leitor");
        jTextFieldNomeEditarLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeEditarLeitorActionPerformed(evt);
            }
        });

        jButtonSalvarEditarLeitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalvarEditarLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ok.png"))); // NOI18N
        jButtonSalvarEditarLeitor.setText("Salvar");
        jButtonSalvarEditarLeitor.setToolTipText("Confirmar");
        jButtonSalvarEditarLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarEditarLeitorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Data de Nasc.");

        jButtonCancelarEditarLeitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelarEditarLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel.png"))); // NOI18N
        jButtonCancelarEditarLeitor.setText("Cancelar");
        jButtonCancelarEditarLeitor.setToolTipText("Cancelar");
        jButtonCancelarEditarLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarEditarLeitorActionPerformed(evt);
            }
        });

        jButtonFecharEditarLeitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonFecharEditarLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fechar.png"))); // NOI18N
        jButtonFecharEditarLeitor.setText("Fechar");
        jButtonFecharEditarLeitor.setToolTipText("Fechar");
        jButtonFecharEditarLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharEditarLeitorActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Número");

        jTextFieldNumeroEditarLeitor.setText("545");

        jButtonPesquisarEditarLeitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/lupa.png"))); // NOI18N
        jButtonPesquisarEditarLeitor.setToolTipText("Clique para Pesquisar");
        jButtonPesquisarEditarLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarEditarLeitorActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Clique para pesquisar");

        try {
            jFormattedTextFieldCpfEditarLeitor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldTelefoneEditarLeitor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldCepEditarLeitor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanelCadastroLeitorLayout = new javax.swing.GroupLayout(jPanelCadastroLeitor);
        jPanelCadastroLeitor.setLayout(jPanelCadastroLeitorLayout);
        jPanelCadastroLeitorLayout.setHorizontalGroup(
            jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelCidade)
                                .addComponent(jTextFieldEnderecoEditarLeitor)
                                .addComponent(jTextFieldCidadeEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNumeroEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(30, 30, 30))
                            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(98, 98, 98))
                                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                        .addComponent(jComboBoxUfEditarLeitor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(30, 30, 30)))))
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFormattedTextFieldCepEditarLeitor)
                                .addComponent(jTextFieldBairroEditarLeitor, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap())
            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldDtNascimentoEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldCpfEditarLeitor)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextFieldTelefoneEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldEmailEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNomeEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisarEditarLeitor)
                        .addGap(136, 136, 136))
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButtonSalvarEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelarEditarLeitor)
                .addGap(18, 18, 18)
                .addComponent(jButtonFecharEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCadastroLeitorLayout.setVerticalGroup(
            jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNomeEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jFormattedTextFieldDtNascimentoEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButtonPesquisarEditarLeitor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jFormattedTextFieldCpfEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldTelefoneEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldEmailEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEnderecoEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldBairroEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNumeroEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCidade)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCidadeEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxUfEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldCepEditarLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelCadastroLeitorLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(26, 26, 26)))
                .addGap(34, 34, 34)
                .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvarEditarLeitor)
                    .addGroup(jPanelCadastroLeitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonFecharEditarLeitor)
                        .addComponent(jButtonCancelarEditarLeitor)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(514, 514, 514)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanelCadastroLeitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeEditarLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeEditarLeitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeEditarLeitorActionPerformed

    private void jButtonFecharEditarLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharEditarLeitorActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharEditarLeitorActionPerformed

    private void jButtonCancelarEditarLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarEditarLeitorActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarEditarLeitorActionPerformed

    private void jButtonPesquisarEditarLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarEditarLeitorActionPerformed
        EditarLeitor2 editarLeitor2 = new EditarLeitor2();
        TelaPrincipal.desktopPane.add(editarLeitor2);
        editarLeitor2.setVisible(true);
        
    }//GEN-LAST:event_jButtonPesquisarEditarLeitorActionPerformed

    private void jButtonSalvarEditarLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarEditarLeitorActionPerformed
        Salvo salvo = new Salvo();
        TelaPrincipal.desktopPane.add(salvo);
        salvo.setVisible(true);
    }//GEN-LAST:event_jButtonSalvarEditarLeitorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarEditarLeitor;
    private javax.swing.JButton jButtonFecharEditarLeitor;
    private javax.swing.JButton jButtonPesquisarEditarLeitor;
    private javax.swing.JButton jButtonSalvarEditarLeitor;
    private javax.swing.JComboBox<String> jComboBoxUfEditarLeitor;
    private javax.swing.JFormattedTextField jFormattedTextFieldCepEditarLeitor;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpfEditarLeitor;
    private javax.swing.JFormattedTextField jFormattedTextFieldDtNascimentoEditarLeitor;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefoneEditarLeitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JPanel jPanelCadastroLeitor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBairroEditarLeitor;
    private javax.swing.JTextField jTextFieldCidadeEditarLeitor;
    private javax.swing.JTextField jTextFieldEmailEditarLeitor;
    private javax.swing.JTextField jTextFieldEnderecoEditarLeitor;
    private javax.swing.JTextField jTextFieldNomeEditarLeitor;
    private javax.swing.JTextField jTextFieldNumeroEditarLeitor;
    // End of variables declaration//GEN-END:variables
}
