// fECHAR O PROGRAMA TODO: System.exit(0);
//Fechar só a janela atual: this.dispose();
/*jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       ConsultaAutor2 consultarAutor2 = new ConsultaAutor2();
       TelaPrincipal.desktopPane.add(consultarAutor2);
       consultarAutor2.setVisible(true);*/ //CHAMAR OUTRA TELA POR UM BOTÃO.

package view;

/**
 *
 * @author Jefferson Queiroz
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemIncluisaoLeitor = new javax.swing.JMenuItem();
        jMenuItemAlteracaoLeitor = new javax.swing.JMenuItem();
        jMenuItemConsultaLeitor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExclusaoLeitor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemInclusaoLivro = new javax.swing.JMenuItem();
        jMenuItemAlteracaoLivro = new javax.swing.JMenuItem();
        jMenuItemConsultaLivro = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExcluirLivro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuIteminclusaoAutor = new javax.swing.JMenuItem();
        jMenuItemAlteracaoAutor = new javax.swing.JMenuItem();
        jMenuItemConsultaAutor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExcluirAutor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemInclusaoEditora = new javax.swing.JMenuItem();
        jMenuItemAlteracaoEditora = new javax.swing.JMenuItem();
        jMenuItemConsultaEditora = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        javax.swing.JMenuItem jMenuItemExcluirEditora = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItemCadastrarFuncionario = new javax.swing.JMenuItem();
        jMenuItemExcluirFuncionario = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExcluirEmprestimo = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemDevolução = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemConsultaDevolucao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Biblioteca");

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadastro");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        jMenu1.setText("Leitor");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItemIncluisaoLeitor.setText("Inclusão de Leitor");
        jMenuItemIncluisaoLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIncluisaoLeitorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemIncluisaoLeitor);

        jMenuItemAlteracaoLeitor.setText("Alteração de Leitor");
        jMenuItemAlteracaoLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlteracaoLeitorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAlteracaoLeitor);

        jMenuItemConsultaLeitor.setText("Consulta de Leitor");
        jMenuItemConsultaLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaLeitorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemConsultaLeitor);
        jMenu1.add(jSeparator1);

        jMenuItemExclusaoLeitor.setText("Exclusão de Leitor");
        jMenuItemExclusaoLeitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExclusaoLeitorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExclusaoLeitor);

        fileMenu.add(jMenu1);

        jMenu4.setText("Livro");

        jMenuItemInclusaoLivro.setText("Inclusão de Livro");
        jMenuItemInclusaoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInclusaoLivroActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemInclusaoLivro);

        jMenuItemAlteracaoLivro.setText("Alteração de Livro");
        jMenuItemAlteracaoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlteracaoLivroActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAlteracaoLivro);

        jMenuItemConsultaLivro.setText("Consulta de Livro");
        jMenuItemConsultaLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaLivroActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemConsultaLivro);
        jMenu4.add(jSeparator3);

        jMenuItemExcluirLivro.setText("Exclusão de Livro");
        jMenuItemExcluirLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirLivroActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemExcluirLivro);

        fileMenu.add(jMenu4);

        jMenu2.setText("Autor");

        jMenuIteminclusaoAutor.setText("Inclusão de Autor");
        jMenuIteminclusaoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIteminclusaoAutorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuIteminclusaoAutor);

        jMenuItemAlteracaoAutor.setText("Alteração de Autor");
        jMenuItemAlteracaoAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlteracaoAutorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAlteracaoAutor);

        jMenuItemConsultaAutor.setText("Consulta de Autor");
        jMenuItemConsultaAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaAutorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemConsultaAutor);
        jMenu2.add(jSeparator2);

        jMenuItemExcluirAutor.setText("Exclusão de Autor");
        jMenuItemExcluirAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirAutorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemExcluirAutor);

        fileMenu.add(jMenu2);

        jMenu3.setText("Editora");

        jMenuItemInclusaoEditora.setText("Inclusão de Editora");
        jMenuItemInclusaoEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInclusaoEditoraActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemInclusaoEditora);

        jMenuItemAlteracaoEditora.setText("Alteração de Editora");
        jMenuItemAlteracaoEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlteracaoEditoraActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAlteracaoEditora);

        jMenuItemConsultaEditora.setText("Consulta de Editora");
        jMenuItemConsultaEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaEditoraActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemConsultaEditora);
        jMenu3.add(jSeparator4);

        jMenuItemExcluirEditora.setText("Exclusão de Editora");
        jMenuItemExcluirEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirEditoraActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemExcluirEditora);

        fileMenu.add(jMenu3);

        jMenu8.setText("Usuário");

        jMenuItemCadastrarFuncionario.setText("Cadastar Usuário");
        jMenuItemCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarFuncionarioActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItemCadastrarFuncionario);

        jMenuItemExcluirFuncionario.setText("Excluir Usuário");
        jMenuItemExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirFuncionarioActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItemExcluirFuncionario);

        fileMenu.add(jMenu8);

        jMenuItem20.setText("Sair do Programa");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem20);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Movimentação");

        jMenu5.setText("Empréstimo");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem18.setText("Fazer Empréstimo");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem18);

        jMenuItem19.setText("Consulta de Empréstimo");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem19);
        jMenu5.add(jSeparator5);

        jMenuItemExcluirEmprestimo.setText("Exclusão de Empréstimo");
        jMenuItemExcluirEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirEmprestimoActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemExcluirEmprestimo);

        editMenu.add(jMenu5);

        jMenu6.setText("Devolução");

        jMenuItemDevolução.setText("Fazer Devolução");
        jMenuItemDevolução.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDevoluçãoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemDevolução);
        jMenu6.add(jSeparator6);

        jMenuItemConsultaDevolucao.setText("Consultar Devolução");
        jMenuItemConsultaDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultaDevolucaoActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemConsultaDevolucao);

        editMenu.add(jMenu6);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
              
                       
                        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItemIncluisaoLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIncluisaoLeitorActionPerformed
                CadastroLeitor cadastroLeitor = new CadastroLeitor();
               // cadastroLeitor.setLocationRelativeTo(true); SERIA PARA A TELA ABRIR NO MEIO
                this.desktopPane.add(cadastroLeitor);
                cadastroLeitor.setVisible(true);
                
    }//GEN-LAST:event_jMenuItemIncluisaoLeitorActionPerformed

    private void jMenuIteminclusaoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIteminclusaoAutorActionPerformed
        CadastroAutor cadastroAutor = new CadastroAutor();
        this.desktopPane.add(cadastroAutor);
        cadastroAutor.setVisible(true);
    }//GEN-LAST:event_jMenuIteminclusaoAutorActionPerformed

    private void jMenuItemInclusaoEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInclusaoEditoraActionPerformed
        CadastroEditora cadastroEditora = new CadastroEditora();
        this.desktopPane.add(cadastroEditora);
        cadastroEditora.setVisible(true);
    }//GEN-LAST:event_jMenuItemInclusaoEditoraActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
      
    }//GEN-LAST:event_fileMenuActionPerformed

    private void jMenuItemConsultaEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaEditoraActionPerformed
       ConsultaEditora pesquisaEditora = new ConsultaEditora();
       this.desktopPane.add(pesquisaEditora);
       pesquisaEditora.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaEditoraActionPerformed

    private void jMenuItemInclusaoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInclusaoLivroActionPerformed
        CadastroLivro cadastroLivro = new CadastroLivro();
        this.desktopPane.add(cadastroLivro);
        cadastroLivro.setVisible(true);
    }//GEN-LAST:event_jMenuItemInclusaoLivroActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
                Emprestimo emprestimo = new Emprestimo();
                this.desktopPane.add(emprestimo);
                emprestimo.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItemAlteracaoLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlteracaoLeitorActionPerformed
        EditarLeitor alterarLeitor = new EditarLeitor();
        this.desktopPane.add(alterarLeitor);
        alterarLeitor.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlteracaoLeitorActionPerformed

    private void jMenuItemConsultaLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaLeitorActionPerformed
       ConsultaLeitor consultarLeitor = new ConsultaLeitor();
        this.desktopPane.add(consultarLeitor);
        consultarLeitor.setVisible(true);
       
      //ConsultaLeitorDois consultaDois = new ConsultaLeitorDois();
     // this.desktopPane.add(consultaDois);
      //consultaDois.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaLeitorActionPerformed

    private void jMenuItemAlteracaoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlteracaoLivroActionPerformed
       EditarLivro alterarLivro = new EditarLivro();
       this.desktopPane.add(alterarLivro);
       alterarLivro.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlteracaoLivroActionPerformed

    private void jMenuItemAlteracaoAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlteracaoAutorActionPerformed
        EditarAutor auterarAutor = new EditarAutor();
        this.desktopPane.add(auterarAutor);
        auterarAutor.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlteracaoAutorActionPerformed

    private void jMenuItemConsultaLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaLivroActionPerformed
        ConsultaLivro consultarLivro = new ConsultaLivro();
        TelaPrincipal.desktopPane.add(consultarLivro);
        consultarLivro.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemConsultaLivroActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItemConsultaAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaAutorActionPerformed
       ConsultaAutor consultaAutor = new ConsultaAutor();
       this.desktopPane.add(consultaAutor);
       consultaAutor.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaAutorActionPerformed

    private void jMenuItemAlteracaoEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlteracaoEditoraActionPerformed
       EditarEditora editarEditora = new EditarEditora();
       this.desktopPane.add(editarEditora);
       editarEditora.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlteracaoEditoraActionPerformed

    private void jMenuItemExclusaoLeitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExclusaoLeitorActionPerformed
       ExcluirLeitor excluirLeitor = new ExcluirLeitor();
       this.desktopPane.add(excluirLeitor);
       excluirLeitor.setVisible(true);
    }//GEN-LAST:event_jMenuItemExclusaoLeitorActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
       ConsultaEmprestimo consultaEmprestimo = new ConsultaEmprestimo();
       this.desktopPane.add(consultaEmprestimo);
       consultaEmprestimo.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
       
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItemExcluirEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirEmprestimoActionPerformed
        ExcluirEmprestimo excluirEmprestimo = new ExcluirEmprestimo();
       this.desktopPane.add(excluirEmprestimo);
       excluirEmprestimo.setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirEmprestimoActionPerformed

    private void jMenuItemDevoluçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDevoluçãoActionPerformed
        Devolucao devolucao = new Devolucao();
        this.desktopPane.add(devolucao);
        devolucao.setVisible(true);
    }//GEN-LAST:event_jMenuItemDevoluçãoActionPerformed

    private void jMenuItemConsultaDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultaDevolucaoActionPerformed
       ConsultaDevolucao consultaDevolucao = new ConsultaDevolucao();
       this.desktopPane.add(consultaDevolucao);
       consultaDevolucao.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultaDevolucaoActionPerformed

    private void jMenuItemCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarFuncionarioActionPerformed
       CadastroUsuario cadastroFuncionario = new CadastroUsuario();
       this.desktopPane.add(cadastroFuncionario);
       cadastroFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarFuncionarioActionPerformed

    private void jMenuItemExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirFuncionarioActionPerformed
        ExcluirUsuario excluirFuncionario = new ExcluirUsuario();
        this.desktopPane.add(excluirFuncionario);
        excluirFuncionario.setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirFuncionarioActionPerformed

    private void jMenuItemExcluirLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirLivroActionPerformed
        ExcluirLivro excluirLivro = new ExcluirLivro();
        this.desktopPane.add(excluirLivro);
        excluirLivro.setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirLivroActionPerformed

    private void jMenuItemExcluirAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirAutorActionPerformed
       ExcluirAutor excluirAutor = new ExcluirAutor();
       this.desktopPane.add(excluirAutor);
       excluirAutor.setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirAutorActionPerformed

    private void jMenuItemExcluirEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirEditoraActionPerformed
       ExcluirEditora excluirEditora = new ExcluirEditora();
       this.desktopPane.add(excluirEditora);
       excluirEditora.setVisible(true);
    }//GEN-LAST:event_jMenuItemExcluirEditoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItemAlteracaoAutor;
    private javax.swing.JMenuItem jMenuItemAlteracaoEditora;
    private javax.swing.JMenuItem jMenuItemAlteracaoLeitor;
    private javax.swing.JMenuItem jMenuItemAlteracaoLivro;
    private javax.swing.JMenuItem jMenuItemCadastrarFuncionario;
    private javax.swing.JMenuItem jMenuItemConsultaAutor;
    private javax.swing.JMenuItem jMenuItemConsultaDevolucao;
    private javax.swing.JMenuItem jMenuItemConsultaEditora;
    private javax.swing.JMenuItem jMenuItemConsultaLeitor;
    private javax.swing.JMenuItem jMenuItemConsultaLivro;
    private javax.swing.JMenuItem jMenuItemDevolução;
    private javax.swing.JMenuItem jMenuItemExcluirAutor;
    private javax.swing.JMenuItem jMenuItemExcluirEmprestimo;
    private javax.swing.JMenuItem jMenuItemExcluirFuncionario;
    private javax.swing.JMenuItem jMenuItemExcluirLivro;
    private javax.swing.JMenuItem jMenuItemExclusaoLeitor;
    private javax.swing.JMenuItem jMenuItemIncluisaoLeitor;
    private javax.swing.JMenuItem jMenuItemInclusaoEditora;
    private javax.swing.JMenuItem jMenuItemInclusaoLivro;
    private javax.swing.JMenuItem jMenuIteminclusaoAutor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
